### ISSUE TITLE
Deleted registrations previously marked as scramblers/runners still count toward total

### ISSUE THREAD

**Issue by zekemackay06** [coder13/delegateDashboard#46]
Excuse the terrible screenshot - This competition originally had 20 people marked as scramblers, but two deleted their registrations. The total number of scramblers is still set at 20 with no way to remove them from that count.

![image](https://github.com/coder13/delegateDashboard/assets/42594475/1f87667b-908b-45bb-bf29-1cdabf7f8072)

**Comment by coder13** [comment]
Should be fixed. Can you verify that it is?
